# Generated by Django 5.2.11 on 2026-04-14 01:07

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tail_number', models.CharField(max_length=254)),
                ('make', models.CharField(blank=True, max_length=254)),
                ('model', models.CharField(blank=True, max_length=254)),
                ('serial_number', models.CharField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('purchased', models.DateField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, upload_to=core.models.UploadToSubdir('aircraft_pictures'))),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MX', 'In Maintenance'), ('GROUND', 'Grounded'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=254)),
                ('tach_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('tach_time_offset', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('hobbs_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('hobbs_time_offset', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('hours', 'Hours Update'), ('flight', 'Flight'), ('component', 'Component'), ('squawk', 'Squawk'), ('note', 'Note'), ('oil', 'Oil'), ('fuel', 'Fuel'), ('logbook', 'Logbook'), ('ad', 'Airworthiness Directive'), ('inspection', 'Inspection'), ('document', 'Document'), ('aircraft', 'Aircraft'), ('role', 'Role'), ('major_record', 'Major Repair/Alteration')], max_length=50)),
                ('event_name', models.CharField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.aircraft')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AircraftNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited_timestamp', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftShareToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('privilege', models.CharField(choices=[('status', 'Current Status'), ('maintenance', 'Maintenance Detail')], default='status', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='core.aircraft')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(help_text="Admin label, e.g. 'Club XYZ Pilots - Spring 2026'", max_length=200)),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('invited_name', models.CharField(blank=True, max_length=200)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True)),
                ('use_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank to never expire', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oidc_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='AircraftFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.aircraft')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['feature'],
                'unique_together': {('aircraft', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='AircraftRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('pilot', 'Pilot')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.aircraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'created_at'],
                'unique_together': {('aircraft', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InvitationCodeAircraftRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('pilot', 'Pilot')], max_length=20)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aircraft')),
                ('invitation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_roles', to='core.invitationcode')),
            ],
            options={
                'unique_together': {('invitation_code', 'aircraft')},
            },
        ),
        migrations.CreateModel(
            name='InvitationCodeRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.invitationcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('code', 'user')},
            },
        ),
    ]
