# Generated by Django 4.2.9 on 2024-01-09 04:32

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tail_number', models.CharField(max_length=254)),
                ('make', models.CharField(blank=True, max_length=254)),
                ('model', models.CharField(blank=True, max_length=254)),
                ('serial_number', models.CharField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('purchased', models.DateField(blank=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, upload_to=core.models.random_picture_filename)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MX', 'In Maintenance'), ('GROUND', 'Grounded'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=254)),
                ('flight_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('certificates', models.CharField(blank=True, max_length=254)),
                ('ratings', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('GOOD', 'Good'), ('WARN', 'Warning'), ('BAD', 'No Fly')], default='GOOD', max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited_timestamp', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=254)),
                ('event_name', models.CharField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='permitted_pilots',
            field=models.ManyToManyField(related_name='allowed_aircraft', to='core.pilot'),
        ),
    ]
