# Generated by Django 4.2.9 on 2024-01-14 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aircraft_permitted_pilots_delete_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftevent',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.aircraft'),
        ),
        migrations.AlterField(
            model_name='aircraftnote',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.aircraft'),
        ),
    ]
