# Generated by Django 4.2.9 on 2026-02-14 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_aircraftevent_aircraft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='aircraftevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aircraftevent',
            name='category',
            field=models.CharField(choices=[('hours', 'Hours Update'), ('component', 'Component'), ('squawk', 'Squawk'), ('note', 'Note'), ('oil', 'Oil'), ('fuel', 'Fuel'), ('logbook', 'Logbook'), ('ad', 'Airworthiness Directive'), ('inspection', 'Inspection'), ('document', 'Document'), ('aircraft', 'Aircraft')], max_length=50),
        ),
    ]
