# Generated by Django 4.2.9 on 2026-02-16 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_aircraftevent_options_aircraftevent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='public_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='share_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='share_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftevent',
            name='category',
            field=models.CharField(choices=[('hours', 'Hours Update'), ('component', 'Component'), ('squawk', 'Squawk'), ('note', 'Note'), ('oil', 'Oil'), ('fuel', 'Fuel'), ('logbook', 'Logbook'), ('ad', 'Airworthiness Directive'), ('inspection', 'Inspection'), ('document', 'Document'), ('aircraft', 'Aircraft'), ('role', 'Role')], max_length=50),
        ),
        migrations.CreateModel(
            name='AircraftRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('pilot', 'Pilot')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.aircraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'created_at'],
                'unique_together': {('aircraft', 'user')},
            },
        ),
    ]
