# Generated by Django 4.2.9 on 2026-02-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aircraft_public_sharing_enabled_aircraft_share_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftevent',
            name='category',
            field=models.CharField(choices=[('hours', 'Hours Update'), ('component', 'Component'), ('squawk', 'Squawk'), ('note', 'Note'), ('oil', 'Oil'), ('fuel', 'Fuel'), ('logbook', 'Logbook'), ('ad', 'Airworthiness Directive'), ('inspection', 'Inspection'), ('document', 'Document'), ('aircraft', 'Aircraft'), ('role', 'Role'), ('major_record', 'Major Repair/Alteration')], max_length=50),
        ),
    ]
