# Generated by Django 5.2.11 on 2026-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_aircraft_sharing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
