# Generated by Django 5.2.11 on 2026-02-22 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_make_purchased_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(help_text="Admin label, e.g. 'Club XYZ Pilots - Spring 2026'", max_length=200)),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('invited_name', models.CharField(blank=True, max_length=200)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True)),
                ('use_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank to never expire', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationCodeAircraftRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('pilot', 'Pilot')], max_length=20)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aircraft')),
                ('invitation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_roles', to='core.invitationcode')),
            ],
            options={
                'unique_together': {('invitation_code', 'aircraft')},
            },
        ),
        migrations.CreateModel(
            name='InvitationCodeRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.invitationcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('code', 'user')},
            },
        ),
    ]
