# Generated by Django 5.2.11 on 2026-03-02 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aircraft_tach_hobbs_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftevent',
            name='category',
            field=models.CharField(choices=[('hours', 'Hours Update'), ('flight', 'Flight'), ('component', 'Component'), ('squawk', 'Squawk'), ('note', 'Note'), ('oil', 'Oil'), ('fuel', 'Fuel'), ('logbook', 'Logbook'), ('ad', 'Airworthiness Directive'), ('inspection', 'Inspection'), ('document', 'Document'), ('aircraft', 'Aircraft'), ('role', 'Role'), ('major_record', 'Major Repair/Alteration')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oidc_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
