# External Secret (Optional)
# Use this if you have External Secrets Operator with Vault or another secret backend
# Otherwise, create a plain Kubernetes Secret (see alternative below)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sam
  namespace: sam
  annotations:
    # Uncomment if using ArgoCD
    # argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault  # Update to match your ClusterSecretStore name
  target:
    name: sam
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: sam  # Vault path containing the secrets

---
# Alternative: Plain Kubernetes Secret
# If NOT using External Secrets Operator, uncomment and use this instead:
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: sam
#   namespace: sam
# type: Opaque
# stringData:
#   # Required: Django secret key (generate with django.core.management.utils.get_random_secret_key())
#   DJANGO_SECRET_KEY: "changeme-random-50-character-string-here"
#
#   # Required: Superuser credentials (created on first startup)
#   DJANGO_SUPERUSER_USERNAME: "admin"
#   DJANGO_SUPERUSER_PASSWORD: "changeme"
#   DJANGO_SUPERUSER_EMAIL: "admin@example.com"
#
#   # Optional: OIDC client credentials (only if OIDC_ENABLED=true)
#   OIDC_RP_CLIENT_ID: "your-oidc-client-id"
#   OIDC_RP_CLIENT_SECRET: "your-oidc-client-secret"

# To generate a Django secret key:
# python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
