"""
Django settings for simple_aircraft_manager project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rb+)rbu9-i70(4jas&2d@0ez!vy8rd8x0p2!v+y)=pf7wby2=c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ]
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'core',
    'health',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'simple_aircraft_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.oidc_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'simple_aircraft_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

LOGIN_REDIRECT_URL = '/dashboard'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logbook import AI model configuration
LOGBOOK_IMPORT_MODELS = [
    {
        'id': 'claude-sonnet-4-5-20250929',
        'name': 'Sonnet 4.5 (recommended)',
        'provider': 'anthropic',
    },
    {
        'id': 'claude-haiku-4-5-20251001',
        'name': 'Haiku 4.5 (faster / cheaper)',
        'provider': 'anthropic',
    },
    {
        'id': 'claude-opus-4-6',
        'name': 'Opus 4.6 (highest quality)',
        'provider': 'anthropic',
    },
    # Example Ollama entry (uncomment and adjust for local models):
    # {
    #     'id': 'llama3.2-vision',
    #     'name': 'Llama 3.2 Vision (local)',
    #     'provider': 'ollama',
    # },
]

LOGBOOK_IMPORT_DEFAULT_MODEL = 'claude-sonnet-4-5-20250929'

# Ollama connection (only needed if any model uses provider=ollama)
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://localhost:11434')

# OIDC Configuration for Development
# Set OIDC_ENABLED=false by default in dev - enable with environment variable for local testing
OIDC_ENABLED = os.environ.get('OIDC_ENABLED', 'False').lower() in ('true', '1', 'yes')

if OIDC_ENABLED:
    # Add mozilla-django-oidc to installed apps
    INSTALLED_APPS.append('mozilla_django_oidc')

    # OIDC Provider Configuration
    # For local Keycloak testing, set these environment variables:
    # OIDC_OP_DISCOVERY_ENDPOINT=http://localhost:8080/realms/master/.well-known/openid-configuration
    # OIDC_RP_CLIENT_ID=simple-aircraft-manager-dev
    # OIDC_RP_CLIENT_SECRET=your-dev-client-secret
    OIDC_OP_DISCOVERY_ENDPOINT = os.environ.get('OIDC_OP_DISCOVERY_ENDPOINT', '')
    OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID', '')
    OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET', '')

    # Fetch OIDC endpoints from discovery document
    if OIDC_OP_DISCOVERY_ENDPOINT:
        import requests
        try:
            discovery_response = requests.get(OIDC_OP_DISCOVERY_ENDPOINT, timeout=10)
            discovery_response.raise_for_status()
            discovery_doc = discovery_response.json()

            OIDC_OP_AUTHORIZATION_ENDPOINT = discovery_doc['authorization_endpoint']
            OIDC_OP_TOKEN_ENDPOINT = discovery_doc['token_endpoint']
            OIDC_OP_USER_ENDPOINT = discovery_doc['userinfo_endpoint']
            OIDC_OP_JWKS_ENDPOINT = discovery_doc.get('jwks_uri')
            OIDC_OP_LOGOUT_ENDPOINT = discovery_doc.get('end_session_endpoint')
        except Exception as e:
            import sys
            print(f"WARNING: Failed to fetch OIDC discovery document from {OIDC_OP_DISCOVERY_ENDPOINT}: {e}", file=sys.stderr)
            print("OIDC authentication will not be available", file=sys.stderr)
            # Don't crash on startup - just disable OIDC
            OIDC_ENABLED = False

    if OIDC_ENABLED and OIDC_OP_DISCOVERY_ENDPOINT:
        # OIDC Optional Configuration
        OIDC_RP_SIGN_ALGO = os.environ.get('OIDC_RP_SIGN_ALGO', 'RS256')
        OIDC_RP_SCOPES = os.environ.get('OIDC_RP_SCOPES', 'openid email profile')

        # Claim Mappings
        OIDC_EMAIL_CLAIM = os.environ.get('OIDC_EMAIL_CLAIM', 'email')
        OIDC_FIRSTNAME_CLAIM = os.environ.get('OIDC_FIRSTNAME_CLAIM', 'given_name')
        OIDC_LASTNAME_CLAIM = os.environ.get('OIDC_LASTNAME_CLAIM', 'family_name')

        # Username Algorithm
        OIDC_USERNAME_ALGO = 'core.oidc.generate_username'

        # Token Expiry (seconds)
        OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = int(os.environ.get('OIDC_TOKEN_EXPIRY', '3600'))

        # Authentication Backends
        AUTHENTICATION_BACKENDS = [
            'core.oidc.CustomOIDCAuthenticationBackend',
            'django.contrib.auth.backends.ModelBackend',  # Fallback for local users
        ]
