# Generated by Django 4.2.9 on 2024-01-09 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import health.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('short_description', models.CharField(max_length=254)),
                ('required_action', models.TextField(blank=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('recurring_months', models.IntegerField(default=0)),
                ('recurring_days', models.IntegerField(default=0)),
                ('applicable_aircraft', models.ManyToManyField(blank=True, related_name='ads', to='core.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('serial_number', models.CharField(blank=True, max_length=254)),
                ('install_location', models.CharField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SPARE', 'Spare Part'), ('IN-USE', 'In Service'), ('DISPOSED', 'Disposed')], default='SPARE', max_length=254)),
                ('date_in_service', models.DateField()),
                ('hours_in_service', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('hours_since_overhaul', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('overhaul_date', models.DateField(blank=True, null=True)),
                ('tbo_hours', models.IntegerField(blank=True, null=True)),
                ('tbo_days', models.IntegerField(blank=True, null=True)),
                ('inspection_hours', models.IntegerField(blank=True, null=True)),
                ('inspection_days', models.IntegerField(blank=True, null=True)),
                ('replacement_hours', models.IntegerField(blank=True, null=True)),
                ('replacement_days', models.IntegerField(blank=True, null=True)),
                ('tbo_critical', models.BooleanField(default=True)),
                ('inspection_critical', models.BooleanField(default=True)),
                ('replacement_critical', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('consumable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('LOG', 'Logbook'), ('ALTER', 'Alteration Record'), ('REPORT', 'Report'), ('ESTIMATE', 'Estimate'), ('DISC', 'Discrepancy List'), ('INVOICE', 'Receipt / Invoice'), ('AIRCRAFT', 'Aircraft Record'), ('OTHER', 'Other')], default='OTHER', max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('ENG', 'Engine'), ('AC', 'Aircraft'), ('PROP', 'Propeller'), ('OTHER', 'Other')], default='AC', max_length=254)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('signoff_person', models.TextField(blank=True)),
                ('signoff_location', models.CharField(blank=True, max_length=254)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='core.aircraft')),
                ('component', models.ManyToManyField(blank=True, related_name='logbook_entries', to='health.component')),
                ('log_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entry', to='health.document')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='related_logs', to='health.document')),
            ],
        ),
        migrations.CreateModel(
            name='STCApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('short_description', models.CharField(max_length=254)),
                ('date_applied', models.DateField()),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stcs', to='core.aircraft')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stcs', to='health.component')),
                ('documents', models.ManyToManyField(blank=True, related_name='stcs', to='health.document')),
                ('logbook_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stcs', to='health.logbookentry')),
            ],
        ),
        migrations.CreateModel(
            name='Squawk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(0, 'Ground Aircraft'), (1, 'Fix Soon'), (2, 'Fix at Next Inspection'), (3, 'Fix Eventually')], default=0)),
                ('issue_reported', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to=health.models.random_squawk_filename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squawks', to='core.aircraft')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squawks', to='health.component')),
                ('logbook_entries', models.ManyToManyField(blank=True, related_name='squawks', to='health.logbookentry')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_squawks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('recurring', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=True)),
                ('recurring_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('recurring_days', models.IntegerField(default=0)),
                ('recurring_months', models.IntegerField(default=0)),
                ('applicable_aircraft', models.ManyToManyField(blank=True, to='core.aircraft')),
                ('applicable_component', models.ManyToManyField(blank=True, to='health.component')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.aircraft')),
                ('component', models.ManyToManyField(blank=True, related_name='inspections', to='health.component')),
                ('documents', models.ManyToManyField(blank=True, related_name='inspections', to='health.document')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.inspectiontype')),
                ('logbook_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='health.logbookentry')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=health.models.random_document_filename)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='health.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_collections', to='core.aircraft')),
                ('components', models.ManyToManyField(blank=True, related_name='doc_collections', to='health.component')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='health.documentcollection'),
        ),
        migrations.AddField(
            model_name='document',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='documents', to='health.component'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.componenttype'),
        ),
        migrations.CreateModel(
            name='ADCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_complied', models.DateField()),
                ('compliance_notes', models.TextField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.ad')),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_compliance', to='core.aircraft')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_compliance', to='health.component')),
                ('inspection_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_complied', to='health.inspectionrecord')),
                ('logbook_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_complied', to='health.logbookentry')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='applicable_component',
            field=models.ManyToManyField(blank=True, related_name='ads', to='health.component'),
        ),
        migrations.AddField(
            model_name='ad',
            name='on_inspection_type',
            field=models.ManyToManyField(blank=True, to='health.inspectiontype'),
        ),
    ]
