# Generated by Django 4.2.9 on 2024-01-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcompliance',
            name='next_due_at_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='adcompliance',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
