# Generated by Django 4.2.9 on 2024-01-14 04:44

from django.db import migrations, models
import health.models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_adcompliance_next_due_at_time_adcompliance_permanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squawk',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=health.models.random_squawk_filename),
        ),
    ]
