# Generated by Django 4.2.9 on 2024-01-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_squawk_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.component'),
        ),
    ]
