# Generated by Django 4.2.9 on 2026-02-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aircraftevent_aircraft_and_more'),
        ('health', '0004_component_parent_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='aircraft_hours_at_entry',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Aircraft total hours at time of entry', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='component_hours',
            field=models.JSONField(blank=True, help_text='Snapshot of component hours {component_id: hours}', null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='entry_type',
            field=models.CharField(choices=[('FLIGHT', 'Flight'), ('MAINTENANCE', 'Maintenance'), ('INSPECTION', 'Inspection'), ('HOURS_UPDATE', 'Hours Update'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='health.component'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='applicable_aircraft',
            field=models.ManyToManyField(blank=True, related_name='applicable_inspections', to='core.aircraft'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='applicable_component',
            field=models.ManyToManyField(blank=True, related_name='applicable_inspections', to='health.component'),
        ),
    ]
