# Generated by Django 4.2.9 on 2026-02-09 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aircraftevent_aircraft_and_more'),
        ('health', '0005_logbookentry_aircraft_hours_at_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity_added', models.DecimalField(decimal_places=2, help_text='Quarts added', max_digits=5)),
                ('level_after', models.DecimalField(blank=True, decimal_places=2, help_text='Oil level after adding (quarts)', max_digits=5, null=True)),
                ('oil_type', models.CharField(blank=True, max_length=100)),
                ('flight_hours', models.DecimalField(decimal_places=1, help_text='Aircraft hours at time of record', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_records', to='core.aircraft')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity_added', models.DecimalField(decimal_places=2, help_text='Gallons added', max_digits=6)),
                ('level_after', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel level after adding (gallons)', max_digits=6, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100)),
                ('flight_hours', models.DecimalField(decimal_places=1, help_text='Aircraft hours at time of record', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='core.aircraft')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
