# Generated by Django 4.2.9 on 2026-02-10 03:15

from django.db import migrations, models
import health.models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_oilrecord_fuelrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.FileField(upload_to=health.models.random_document_filename),
        ),
    ]
