# Generated by Django 4.2.9 on 2026-02-10 03:42

import django.core.validators
from django.db import migrations, models
import health.models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_documentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.FileField(upload_to=health.models.random_document_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tiff', 'pdf', 'txt'])]),
        ),
    ]
