# Generated by Django 4.2.9 on 2026-02-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_alter_documentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='compliance_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('conditional', 'Conditional')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='trigger_condition',
            field=models.TextField(blank=True),
        ),
    ]
