# Generated by Django 4.2.9 on 2026-02-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_ad_compliance_type_ad_trigger_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcompliance',
            name='aircraft_hours_at_compliance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
