# Generated by Django 4.2.9 on 2026-02-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_add_aircraft_hours_to_adcompliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='aircraft_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Aircraft total hours at time of inspection', max_digits=8, null=True),
        ),
    ]
