# Generated by Django 4.2.9 on 2026-02-14 21:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_oil_fuel_to_consumable(apps, schema_editor):
    OilRecord = apps.get_model('health', 'OilRecord')
    FuelRecord = apps.get_model('health', 'FuelRecord')
    ConsumableRecord = apps.get_model('health', 'ConsumableRecord')

    for rec in OilRecord.objects.all():
        ConsumableRecord.objects.create(
            id=rec.id,
            record_type='oil',
            aircraft=rec.aircraft,
            date=rec.date,
            quantity_added=rec.quantity_added,
            level_after=rec.level_after,
            consumable_type=rec.oil_type,
            flight_hours=rec.flight_hours,
            notes=rec.notes,
            created_at=rec.created_at,
        )

    for rec in FuelRecord.objects.all():
        ConsumableRecord.objects.create(
            id=rec.id,
            record_type='fuel',
            aircraft=rec.aircraft,
            date=rec.date,
            quantity_added=rec.quantity_added,
            level_after=rec.level_after,
            consumable_type=rec.fuel_type,
            flight_hours=rec.flight_hours,
            notes=rec.notes,
            created_at=rec.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aircraftevent_options_aircraftevent_user_and_more'),
        ('health', '0011_add_aircraft_hours_to_inspection_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('oil', 'Oil'), ('fuel', 'Fuel')], max_length=10)),
                ('date', models.DateField()),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=6)),
                ('level_after', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('consumable_type', models.CharField(blank=True, help_text="e.g. 'Aeroshell W100' for oil or '100LL' for fuel", max_length=100)),
                ('flight_hours', models.DecimalField(decimal_places=1, help_text='Aircraft hours at time of record', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_records', to='core.aircraft')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RunPython(
            migrate_oil_fuel_to_consumable,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='oilrecord',
            name='aircraft',
        ),
        migrations.DeleteModel(
            name='FuelRecord',
        ),
        migrations.DeleteModel(
            name='OilRecord',
        ),
    ]
