# Generated by Django 4.2.9 on 2026-02-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_consumablerecord_consolidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, help_text='1-based page number within the attached log_image document', null=True),
        ),
    ]
