# Generated by Django 4.2.9 on 2026-02-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
