# Generated by Django 4.2.9 on 2026-02-16 22:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aircraftevent_category'),
        ('health', '0015_document_shared_documentcollection_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorRepairAlteration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('repair', 'Major Repair'), ('alteration', 'Major Alteration')], max_length=20)),
                ('title', models.CharField(help_text="Brief title, e.g. 'Longeron repair' or 'STC SA00001SE installation'", max_length=254)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the work performed')),
                ('date_performed', models.DateField(help_text='Date the repair or alteration was completed')),
                ('performed_by', models.CharField(blank=True, help_text='Mechanic, shop, or IA who performed the work', max_length=254)),
                ('form_337_number', models.CharField(blank=True, help_text='FAA Form 337 number, if assigned', max_length=100)),
                ('stc_number', models.CharField(blank=True, help_text='STC number (e.g. SA00001SE), if this alteration was done under an STC', max_length=100)),
                ('stc_holder', models.CharField(blank=True, help_text='STC holder / manufacturer name', max_length=254)),
                ('aircraft_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Aircraft total hours at time of work', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_records', to='core.aircraft')),
                ('component', models.ForeignKey(blank=True, help_text='Component this applies to (engine, prop, etc.), if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_records', to='health.component')),
                ('form_337_document', models.ForeignKey(blank=True, help_text='Scanned/uploaded Form 337 document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_337_records', to='health.document')),
                ('logbook_entry', models.ForeignKey(blank=True, help_text='Associated logbook entry recording this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_records', to='health.logbookentry')),
                ('stc_document', models.ForeignKey(blank=True, help_text='STC paperwork / data package document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stc_records', to='health.document')),
            ],
            options={
                'ordering': ['-date_performed', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='STCApplication',
        ),
    ]
