# Generated by Django 4.2.9 on 2026-02-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_majorrepairalteration_delete_stcapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorrepairalteration',
            name='form_337_number',
        ),
    ]
