# Generated by Django 5.2.11 on 2026-02-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_import_job_nullable_aircraft_add_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='documentimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
