# Generated by Django 5.2.11 on 2026-02-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0022_majorrepairalteration_ica_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='bulletin_type',
            field=models.CharField(choices=[('ad', 'Airworthiness Directive'), ('saib', 'Special Airworthiness Information Bulletin'), ('sb', 'Service Bulletin'), ('alert', 'Airworthiness Alert'), ('other', 'Other')], default='ad', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
