# Generated by Django 5.2.11 on 2026-02-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_ad_bulletin_type_ad_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Optional reference to a document (e.g., copy of the bulletin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_ads', to='health.document'),
        ),
    ]
