# Generated by Django 5.2.11 on 2026-02-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0024_ad_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='on_condition',
            field=models.BooleanField(default=False),
        ),
    ]
