# Generated by Django 5.2.11 on 2026-02-25 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invitationcode_invitationcodeaircraftrole_and_more'),
        ('health', '0025_component_on_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilAnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_date', models.DateField()),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('lab', models.CharField(blank=True, max_length=200)),
                ('lab_number', models.CharField(blank=True, max_length=100)),
                ('oil_type', models.CharField(blank=True, max_length=200)),
                ('oil_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('oil_added_quarts', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('elements_ppm', models.JSONField(blank=True, default=dict)),
                ('oil_properties', models.JSONField(blank=True, null=True)),
                ('lab_comments', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('monitor', 'Monitor'), ('action_required', 'Action Required')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_analysis_reports', to='core.aircraft')),
                ('component', models.ForeignKey(blank=True, help_text='Engine component this sample is from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_analysis_reports', to='health.component')),
            ],
            options={
                'ordering': ['-sample_date', '-created_at'],
            },
        ),
    ]
