# Generated by Django 5.2.11 on 2026-02-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0026_oilanalysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(blank=True, choices=[('logbook', 'Logbook Import'), ('oil_analysis', 'Oil Analysis Extraction'), ('aircraft', 'Aircraft Import')], default='', max_length=20),
        ),
    ]
