# Generated by Django 5.2.11 on 2026-02-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0027_importjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablerecord',
            name='excluded_from_averages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oilanalysisreport',
            name='excluded_from_averages',
            field=models.BooleanField(default=False),
        ),
    ]
