# Generated by Django 5.2.11 on 2026-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0029_flightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='fuel_level_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fuel level (gal) after addition', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='oil_level_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total oil level (qt) after addition', max_digits=6, null=True),
        ),
    ]
