# Generated by Django 5.2.11 on 2026-04-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0030_add_level_after_to_flight_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimage',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squawk',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
